import { jsPDF } from 'jspdf';
import { Project } from '@/types';

export function exportProjectToPDF(project: Project) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Colors
    const primaryColor: [number, number, number] = [234, 179, 8]; // Yellow-500
    const darkColor: [number, number, number] = [15, 23, 42]; // Slate-900

    // Header
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(...darkColor);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('BuildCompare SA', 14, 20);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Project Materials Export', 14, 30);

    // Project Details
    let yPos = 55;

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(project.name, 14, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(`Location: ${project.location}`, 14, yPos);
    yPos += 6;
    doc.text(`Status: ${project.status.toUpperCase()}`, 14, yPos);
    yPos += 6;
    doc.text(`Created: ${new Date(project.createdAt).toLocaleDateString('en-ZA')}`, 14, yPos);
    yPos += 15;

    // Budget Summary
    doc.setFillColor(241, 245, 249); // Slate-100
    doc.rect(14, yPos, pageWidth - 28, 25, 'F');

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Budget Summary', 20, yPos + 10);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const budgetText = `Total Budget: R${project.totalBudget.toLocaleString('en-ZA')} | Spent: R${project.spent.toLocaleString('en-ZA')} | Remaining: R${(project.totalBudget - project.spent).toLocaleString('en-ZA')}`;
    doc.text(budgetText, 20, yPos + 18);
    yPos += 35;

    // Materials Table Header
    doc.setFillColor(...primaryColor);
    doc.rect(14, yPos, pageWidth - 28, 10, 'F');

    doc.setTextColor(...darkColor);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Material', 20, yPos + 7);
    doc.text('Category', 80, yPos + 7);
    doc.text('Quantity', 130, yPos + 7);
    doc.text('Unit', 170, yPos + 7);
    yPos += 15;

    // Materials Rows
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);

    project.materials.forEach((material, index) => {
        if (yPos > 270) {
            doc.addPage();
            yPos = 20;
        }

        // Alternate row colors
        if (index % 2 === 0) {
            doc.setFillColor(248, 250, 252);
            doc.rect(14, yPos - 5, pageWidth - 28, 10, 'F');
        }

        doc.text(material.name, 20, yPos);
        doc.text(material.category, 80, yPos);
        doc.text(material.quantity.toString(), 130, yPos);
        doc.text(material.unit, 170, yPos);
        yPos += 10;
    });

    // Footer
    yPos = doc.internal.pageSize.getHeight() - 20;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by BuildCompare SA on ${new Date().toLocaleString('en-ZA')}`, 14, yPos);
    doc.text('www.buildcompare.co.za', pageWidth - 50, yPos);

    // Save
    doc.save(`${project.name.replace(/\s+/g, '_')}_materials.pdf`);
}
