import { jsPDF } from 'jspdf';
import { Project } from '@/types';

/** Title Case helper — preserves uppercase abbreviations like IBR, PVC, PPC */
function toTitleCase(s: string): string {
    return s.replace(/\b\w+/g, (word) => {
        if (word.length <= 3 && word === word.toUpperCase()) return word;
        return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
    });
}

export function exportProjectToPDF(project: Project) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Colors
    const primaryColor: [number, number, number] = [234, 179, 8]; // Yellow-500
    const darkColor: [number, number, number] = [15, 23, 42]; // Slate-900

    // Header
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(...darkColor);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('BuildCompare SA', 14, 20);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Project Materials Export', 14, 30);

    // Project Details
    let yPos = 55;

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(project.name, 14, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(`Location: ${project.location}`, 14, yPos);
    yPos += 6;
    doc.text(`Status: ${project.status.toUpperCase()}`, 14, yPos);
    yPos += 6;
    doc.text(`Created: ${new Date(project.createdAt).toLocaleDateString('en-ZA')}`, 14, yPos);
    yPos += 15;

    // Budget Summary
    doc.setFillColor(241, 245, 249); // Slate-100
    doc.rect(14, yPos, pageWidth - 28, 25, 'F');

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Budget Summary', 20, yPos + 10);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const budgetText = `Allocated Budget: R${project.totalBudget.toLocaleString('en-ZA')} | Spent: R${project.spent.toLocaleString('en-ZA')} | Remaining: R${(project.totalBudget - project.spent).toLocaleString('en-ZA')}`;
    doc.text(budgetText, 20, yPos + 18);
    yPos += 35;

    // Materials Table Header
    doc.setFillColor(...primaryColor);
    doc.rect(14, yPos, pageWidth - 28, 10, 'F');

    doc.setTextColor(...darkColor);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text('Material', 16, yPos + 7);
    doc.text('Category', 70, yPos + 7);
    doc.text('Qty', 110, yPos + 7);
    doc.text('Mat. Cost', 130, yPos + 7);
    doc.text('Labour', 160, yPos + 7);
    doc.text('Total', 185, yPos + 7);
    yPos += 15;

    // Materials Rows — apply Title Case
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);

    let projectTotalMaterial = 0;
    let projectTotalLabor = 0;

    project.materials.forEach((material, index) => {
        if (yPos > 260) {
            doc.addPage();
            yPos = 20;
        }

        // Alternate row colors
        if (index % 2 === 0) {
            doc.setFillColor(248, 250, 252);
            doc.rect(14, yPos - 5, pageWidth - 28, 10, 'F');
        }

        const materialCost = (material._aiPriceEstimate || 0) * material.quantity;
        const laborCost = (material.laborCostEstimate || 0) * material.quantity;
        const totalCost = materialCost + laborCost;

        projectTotalMaterial += materialCost;
        projectTotalLabor += laborCost;

        doc.setFontSize(9);
        doc.text(toTitleCase(material.name).substring(0, 30), 16, yPos);
        doc.text(toTitleCase(material.category), 70, yPos);
        doc.text(`${material.quantity} ${material.unit}`, 110, yPos);
        doc.text(materialCost > 0 ? `R${materialCost.toLocaleString('en-ZA')}` : '-', 130, yPos);
        doc.text(laborCost > 0 ? `R${laborCost.toLocaleString('en-ZA')}` : '-', 160, yPos);
        doc.text(totalCost > 0 ? `R${totalCost.toLocaleString('en-ZA')}` : '-', 185, yPos);
        yPos += 10;
    });

    // Project Total Summary
    yPos += 5;
    doc.setFillColor(241, 245, 249);
    doc.rect(14, yPos, pageWidth - 28, 20, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(`Total Material Value: R${projectTotalMaterial.toLocaleString('en-ZA')}`, 20, yPos + 8);
    doc.text(`Total Labour Value: R${projectTotalLabor.toLocaleString('en-ZA')}`, 20, yPos + 14);
    
    const finalTotal = projectTotalMaterial + projectTotalLabor;
    doc.setFontSize(12);
    doc.setTextColor(...primaryColor); // Yellow-500
    doc.text(`Total Site-Ready Estimate: R${finalTotal.toLocaleString('en-ZA')}`, 110, yPos + 12);

    // Footer
    yPos = doc.internal.pageSize.getHeight() - 20;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by BuildCompare SA on ${new Date().toLocaleString('en-ZA')}`, 14, yPos);
    doc.text('www.buildcompare.co.za', pageWidth - 50, yPos);

    // Save
    doc.save(`${project.name.replace(/\s+/g, '_')}_materials.pdf`);
}
